[package]
name = "bfl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.4.7", features = ["derive"] }
colored = "2"
env_logger = "0.10.0"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = [
    "llvm15-0",
] }
log = "0.4.17"
parse-display = "0.8.0"
smallvec = "1.10.0"
string-interner = "0.14.0"
zstd-sys = "2.0.8"
either = "1.9.0"
raylib = "5.0.1"
